// End-to-end interaction test: drives the real UI in headless Chrome and reports errors and speed.
import { chromium } from 'playwright';
const base = process.env.BASE || 'http://127.0.0.1:5180';
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--enable-unsafe-webgpu', '--use-angle=metal', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
const errors = [];
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('404')) errors.push(m.text().slice(0, 300)); });
page.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message));
await page.goto(`${base}/index.html?model=f1`);
await page.waitForFunction(() => window.__ready === true, null, { timeout: 240000 });
const st = () => page.evaluate(() => { const s = window.__app.stats; return { ready: s.ready, fps: +s.fps.toFixed(1), stepsPerSec: Math.round(s.stepsPerSec), cd: +s.cd.toFixed(3), cl: +s.cl.toFixed(3), cy: +s.cy.toFixed(3), settled: +s.settled.toFixed(2), solid: s.solidCells, model: window.__app.state.model }; });
const step = async (label, fn, wait = 1500) => { await fn(); await page.waitForTimeout(wait); console.log(label.padEnd(34), JSON.stringify(await st())); };
await page.waitForTimeout(3000);
await step('F1 default', async () => {});
await step('layer: pressure on', () => page.click('[data-layer="pressure"]'));
await step('layer: slice on', () => page.click('[data-layer="slice"]'));
await step('slice mode pressure', () => page.click('#sliceMode [data-mode="1"]'));
await step('slice axis x', () => page.click('#sliceAxis [data-axis="0"]'));
await step('layer: vortex on (all layers)', () => page.click('[data-layer="vortex"]'), 3500);
await step('yaw 10 deg', () => page.$eval('#yaw', (el) => { el.value = '10'; el.dispatchEvent(new Event('input', { bubbles: true })); }), 2500);
await step('speed max', () => page.$eval('#speed', (el) => { el.value = el.max; el.dispatchEvent(new Event('input', { bubbles: true })); }), 2500);
await step('pause', () => page.click('#btnPause'), 800);
await step('resume', () => page.click('#btnPause'), 800);
await step('reset flow', () => page.click('#btnReset'), 1500);
await step('camera: top', () => page.click('[data-view="top"]'), 1200);
await step('switch to A380', async () => { await page.click('[data-model="a380"]'); await page.waitForFunction(() => window.__app.stats.ready && window.__app.state.model === 'a380', null, { timeout: 120000 }); }, 4000);
await step('A380 aoa 12', () => page.$eval('#aoa', (el) => { el.value = '12'; el.dispatchEvent(new Event('input', { bubbles: true })); }), 3000);
await step('A380 aoa -2 (rapid changes)', async () => { for (const v of ['0', '4', '8', '-2']) { await page.$eval('#aoa', (el, v) => { el.value = v; el.dispatchEvent(new Event('input', { bubbles: true })); }, v); await page.waitForTimeout(150); } }, 3000);
await step('A380 layers off, streams only', async () => { for (const l of ['pressure', 'slice', 'vortex']) await page.click(`[data-layer="${l}"]`); }, 2500);
await step('back to F1', async () => { await page.click('[data-model="f1"]'); await page.waitForFunction(() => window.__app.stats.ready && window.__app.state.model === 'f1', null, { timeout: 120000 }); }, 3000);
await step('open maths + validation', async () => { await page.click('#btnMaths'); await page.click('#btnValid'); }, 1200);
await page.screenshot({ path: '/private/tmp/claude-501/shots/e2e_valid.png' });
console.log('errors:', errors.length ? errors : 'none');
await browser.close();
